





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;


namespace GlassMapperWalkthrough.Domain.Models
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; set; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        string Url { get; set; }

		[SitecoreInfo(SitecoreInfoType.Name)]
        string Name { get; set; }

		[SitecoreField("__Sortorder")]
        int Sortorder { get; set; }

		[SitecoreInfo(SitecoreInfoType.BaseTemplateIds)]
        IEnumerable<Guid> BaseTemplateIds { get; set; }

        [SitecoreInfo(SitecoreInfoType.ContentPath)]
        string ContentPath { get; set; }

        [SitecoreInfo(SitecoreInfoType.DisplayName)]
        string DisplayName { get; set; }

        [SitecoreInfo(SitecoreInfoType.FullPath)]
        string FullPath { get; set; }

        [SitecoreInfo(SitecoreInfoType.Path)]
        string Path { get; set; }

        [SitecoreInfo(SitecoreInfoType.TemplateId)]
        Guid TemplateId { get; set; }

        [SitecoreInfo(SitecoreInfoType.TemplateName)]
        string TemplateName { get; set; }

        [SitecoreChildren(InferType = true)]
        IEnumerable<IGlassBase> Children { get; set; }

        [SitecoreParent(InferType = true)]
        IGlassBase Parent { get; set; }
	}
}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders
{


 	/// <summary>
	/// IMain_Navigation_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Shared Content/Folders/Main Navigation Folder</para>	
	/// <para>ID: 1b3f58c5-e8fd-4926-a97a-c93b74e386fa</para>	
	/// </summary>
	[SitecoreType(TemplateId=IMain_Navigation_Folder_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IMain_Navigation_Folder : IGlassBase , global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders.IFolder
	{
		}

	public static partial class IMain_Navigation_Folder_Constants{

			public const string TemplateIdString = "1b3f58c5-e8fd-4926-a97a-c93b74e386fa";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Main Navigation Folder";

			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders
{


 	/// <summary>
	/// IHeader_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Shared Content/Folders/Header Folder</para>	
	/// <para>ID: 28890e72-ffbf-4e36-b3db-1215381a3cf3</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHeader_Folder_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IHeader_Folder : IGlassBase , global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders.IFolder
	{
		}

	public static partial class IHeader_Folder_Constants{

			public const string TemplateIdString = "28890e72-ffbf-4e36-b3db-1215381a3cf3";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Header Folder";

			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Items
{


 	/// <summary>
	/// IText_Link Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Shared Content/Items/Text Link</para>	
	/// <para>ID: 2a4160fb-cb3c-4655-920c-a73c187703b7</para>	
	/// </summary>
	[SitecoreType(TemplateId=IText_Link_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IText_Link : IGlassBase 
	{
			
					/// <summary>
			/// The Link field.
			/// <para></para>
			/// <para>Field Type: General Link</para>		
			/// <para>Field ID: 66b7bea7-b2dc-446e-9878-003799eb99fc</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IText_Link_Constants.Link_FieldName)]
						Link Link  { get; set; }
					
					/// <summary>
			/// The Title field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: 18489f03-048b-4b95-831b-7ae01bb7ced2</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IText_Link_Constants.Title_FieldName)]
						string Title  { get; set; }
				}

	public static partial class IText_Link_Constants{

			public const string TemplateIdString = "2a4160fb-cb3c-4655-920c-a73c187703b7";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Text Link";

					
			public static readonly Guid Link_FieldId = new Guid("66b7bea7-b2dc-446e-9878-003799eb99fc");
			public const string Link_FieldName = "Link";
			
					
			public static readonly Guid Title_FieldId = new Guid("18489f03-048b-4b95-831b-7ae01bb7ced2");
			public const string Title_FieldName = "Title";
			
			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Pages
{


 	/// <summary>
	/// IGeneric_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Pages/Generic Page</para>	
	/// <para>ID: 2dfcc795-76a0-4467-9117-f50b63970008</para>	
	/// </summary>
	[SitecoreType(TemplateId=IGeneric_Page_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IGeneric_Page : IGlassBase 
	{
		}

	public static partial class IGeneric_Page_Constants{

			public const string TemplateIdString = "2dfcc795-76a0-4467-9117-f50b63970008";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Generic Page";

			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders
{


 	/// <summary>
	/// IFooter_Bottom_Links_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Shared Content/Folders/Footer Bottom Links Folder</para>	
	/// <para>ID: 3bc272b1-94a2-4c08-970b-5c25b6a09e23</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFooter_Bottom_Links_Folder_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IFooter_Bottom_Links_Folder : IGlassBase , global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders.IFolder
	{
		}

	public static partial class IFooter_Bottom_Links_Folder_Constants{

			public const string TemplateIdString = "3bc272b1-94a2-4c08-970b-5c25b6a09e23";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Footer Bottom Links Folder";

			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders
{


 	/// <summary>
	/// IFolder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Shared Content/Folders/Folder</para>	
	/// <para>ID: 3ce15cbd-3bb2-46f8-bbcb-1ced30c49664</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFolder_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IFolder : IGlassBase 
	{
		}

	public static partial class IFolder_Constants{

			public const string TemplateIdString = "3ce15cbd-3bb2-46f8-bbcb-1ced30c49664";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Folder";

			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders
{


 	/// <summary>
	/// IGeneric_Callouts_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Shared Content/Folders/Generic Callouts Folder</para>	
	/// <para>ID: 3e5d70bb-dd95-4ea9-8f0d-f637e04c202b</para>	
	/// </summary>
	[SitecoreType(TemplateId=IGeneric_Callouts_Folder_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IGeneric_Callouts_Folder : IGlassBase , global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders.IFolder
	{
		}

	public static partial class IGeneric_Callouts_Folder_Constants{

			public const string TemplateIdString = "3e5d70bb-dd95-4ea9-8f0d-f637e04c202b";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Generic Callouts Folder";

			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Items
{


 	/// <summary>
	/// IGeneric_Callout Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Shared Content/Items/Generic Callout</para>	
	/// <para>ID: 454424e1-684d-4ad9-8f2a-8ff070e21eab</para>	
	/// </summary>
	[SitecoreType(TemplateId=IGeneric_Callout_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IGeneric_Callout : IGlassBase 
	{
						/// <summary>
			/// The Body Content field.
			/// <para></para>
			/// <para>Field Type: Rich Text</para>		
			/// <para>Field ID: 057fa8e7-cdb7-476a-82e2-594421b17bb4</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IGeneric_Callout_Constants.Body_Content_FieldName, ReadOnly = true)]
						string Body_Content  { get; set; }

			/// <summary>
			/// The Body Content field in RAW format.
			/// <para></para>
			/// <para>Field Type: Rich Text</para>		
			/// <para>Field ID: 057fa8e7-cdb7-476a-82e2-594421b17bb4</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IGeneric_Callout_Constants.Body_Content_FieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
						string Body_Content_Raw  { get; set; }
		
					
					/// <summary>
			/// The Headline field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: 1d57731f-cc1b-4dc8-8a8e-557d9aedec6a</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IGeneric_Callout_Constants.Headline_FieldName)]
						string Headline  { get; set; }
					
					/// <summary>
			/// The Image field.
			/// <para></para>
			/// <para>Field Type: Image</para>		
			/// <para>Field ID: bb038392-ce71-403c-b47c-2ae738173fa6</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IGeneric_Callout_Constants.Image_FieldName)]
						Image Image  { get; set; }
					
					/// <summary>
			/// The Link field.
			/// <para></para>
			/// <para>Field Type: General Link</para>		
			/// <para>Field ID: 04f8a871-2a18-4210-b2e5-daf0726f2565</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IGeneric_Callout_Constants.Link_FieldName)]
						Link Link  { get; set; }
				}

	public static partial class IGeneric_Callout_Constants{

			public const string TemplateIdString = "454424e1-684d-4ad9-8f2a-8ff070e21eab";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Generic Callout";

					
			public static readonly Guid Body_Content_FieldId = new Guid("057fa8e7-cdb7-476a-82e2-594421b17bb4");
			public const string Body_Content_FieldName = "Body Content";
			
					
			public static readonly Guid Headline_FieldId = new Guid("1d57731f-cc1b-4dc8-8a8e-557d9aedec6a");
			public const string Headline_FieldName = "Headline";
			
					
			public static readonly Guid Image_FieldId = new Guid("bb038392-ce71-403c-b47c-2ae738173fa6");
			public const string Image_FieldName = "Image";
			
					
			public static readonly Guid Link_FieldId = new Guid("04f8a871-2a18-4210-b2e5-daf0726f2565");
			public const string Link_FieldName = "Link";
			
			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Rendering_Parameters
{


 	/// <summary>
	/// ICarousel_Rendering_Parameters Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Rendering Parameters/Carousel Rendering Parameters</para>	
	/// <para>ID: 4cf49975-a454-43c6-9134-40b3a3dc15ef</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICarousel_Rendering_Parameters_Constants.TemplateIdString )] //, Cachable = true
	public partial interface ICarousel_Rendering_Parameters : IGlassBase 
	{
			
					/// <summary>
			/// The Display Previous And Next Buttons field.
			/// <para></para>
			/// <para>Field Type: Checkbox</para>		
			/// <para>Field ID: fa429c8e-8176-4baa-a71c-551d28d1b93d</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(ICarousel_Rendering_Parameters_Constants.Display_Previous_And_Next_Buttons_FieldName)]
						bool Display_Previous_And_Next_Buttons  { get; set; }
				}

	public static partial class ICarousel_Rendering_Parameters_Constants{

			public const string TemplateIdString = "4cf49975-a454-43c6-9134-40b3a3dc15ef";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Carousel Rendering Parameters";

					
			public static readonly Guid Display_Previous_And_Next_Buttons_FieldId = new Guid("fa429c8e-8176-4baa-a71c-551d28d1b93d");
			public const string Display_Previous_And_Next_Buttons_FieldName = "Display Previous And Next Buttons";
			
			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Items
{


 	/// <summary>
	/// ICarousel_Slide Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Shared Content/Items/Carousel Slide</para>	
	/// <para>ID: 56351833-86ab-48c0-83df-2ead9bcca728</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICarousel_Slide_Constants.TemplateIdString )] //, Cachable = true
	public partial interface ICarousel_Slide : IGlassBase , global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Items.IBase_Content
	{
			
					/// <summary>
			/// The Image field.
			/// <para></para>
			/// <para>Field Type: Image</para>		
			/// <para>Field ID: db18456c-c5b6-43ab-a56f-29efa480af63</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(ICarousel_Slide_Constants.Image_FieldName)]
						Image Image  { get; set; }
				}

	public static partial class ICarousel_Slide_Constants{

			public const string TemplateIdString = "56351833-86ab-48c0-83df-2ead9bcca728";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Carousel Slide";

					
			public static readonly Guid Image_FieldId = new Guid("db18456c-c5b6-43ab-a56f-29efa480af63");
			public const string Image_FieldName = "Image";
			
			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Items
{


 	/// <summary>
	/// IBase_Content Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Shared Content/Items/Base Content</para>	
	/// <para>ID: 5a1a9bf2-e78d-41ca-8dec-fde194fbf35e</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBase_Content_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IBase_Content : IGlassBase 
	{
		}

	public static partial class IBase_Content_Constants{

			public const string TemplateIdString = "5a1a9bf2-e78d-41ca-8dec-fde194fbf35e";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Base Content";

			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders
{


 	/// <summary>
	/// IGlobals_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Shared Content/Folders/Globals Folder</para>	
	/// <para>ID: 5b2ea3fb-7585-4457-adac-f7781a96dace</para>	
	/// </summary>
	[SitecoreType(TemplateId=IGlobals_Folder_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IGlobals_Folder : IGlassBase , global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders.IFolder
	{
		}

	public static partial class IGlobals_Folder_Constants{

			public const string TemplateIdString = "5b2ea3fb-7585-4457-adac-f7781a96dace";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Globals Folder";

			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Items
{


 	/// <summary>
	/// IUtility_Navigation Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Shared Content/Items/Utility Navigation</para>	
	/// <para>ID: 68d95cb2-d055-4c17-a5a0-522678111a29</para>	
	/// </summary>
	[SitecoreType(TemplateId=IUtility_Navigation_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IUtility_Navigation : IGlassBase 
	{
			
					/// <summary>
			/// The Title field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: eefcf249-9d55-49c4-bae3-e463d5288117</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IUtility_Navigation_Constants.Title_FieldName)]
						string Title  { get; set; }
				}

	public static partial class IUtility_Navigation_Constants{

			public const string TemplateIdString = "68d95cb2-d055-4c17-a5a0-522678111a29";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Utility Navigation";

					
			public static readonly Guid Title_FieldId = new Guid("eefcf249-9d55-49c4-bae3-e463d5288117");
			public const string Title_FieldName = "Title";
			
			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Pages.Base_Content
{


 	/// <summary>
	/// IList_Item Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Pages/Base Content/List Item</para>	
	/// <para>ID: 6bf231a6-14c0-419c-8f68-491b10f3598f</para>	
	/// </summary>
	[SitecoreType(TemplateId=IList_Item_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IList_Item : IGlassBase 
	{
			
					/// <summary>
			/// The Link Label field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: dc54c8dc-08f7-4123-acbf-865a39b90947</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IList_Item_Constants.Link_Label_FieldName)]
						string Link_Label  { get; set; }
								/// <summary>
			/// The Short Description field.
			/// <para></para>
			/// <para>Field Type: Rich Text</para>		
			/// <para>Field ID: a7b0c508-20f9-4e46-9466-a115ab7af677</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IList_Item_Constants.Short_Description_FieldName, ReadOnly = true)]
						string Short_Description  { get; set; }

			/// <summary>
			/// The Short Description field in RAW format.
			/// <para></para>
			/// <para>Field Type: Rich Text</para>		
			/// <para>Field ID: a7b0c508-20f9-4e46-9466-a115ab7af677</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IList_Item_Constants.Short_Description_FieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
						string Short_Description_Raw  { get; set; }
		
					
					/// <summary>
			/// The Thumbnail field.
			/// <para></para>
			/// <para>Field Type: Image</para>		
			/// <para>Field ID: 1d79c2d5-dd2a-4d3f-88a3-a9b3998039f6</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IList_Item_Constants.Thumbnail_FieldName)]
						Image Thumbnail  { get; set; }
				}

	public static partial class IList_Item_Constants{

			public const string TemplateIdString = "6bf231a6-14c0-419c-8f68-491b10f3598f";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "List Item";

					
			public static readonly Guid Link_Label_FieldId = new Guid("dc54c8dc-08f7-4123-acbf-865a39b90947");
			public const string Link_Label_FieldName = "Link Label";
			
					
			public static readonly Guid Short_Description_FieldId = new Guid("a7b0c508-20f9-4e46-9466-a115ab7af677");
			public const string Short_Description_FieldName = "Short Description";
			
					
			public static readonly Guid Thumbnail_FieldId = new Guid("1d79c2d5-dd2a-4d3f-88a3-a9b3998039f6");
			public const string Thumbnail_FieldName = "Thumbnail";
			
			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders
{


 	/// <summary>
	/// ISocial_Media_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Shared Content/Folders/Social Media Folder</para>	
	/// <para>ID: 76f0cd1b-032f-4b7d-9ca3-b82fad99f1ff</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISocial_Media_Folder_Constants.TemplateIdString )] //, Cachable = true
	public partial interface ISocial_Media_Folder : IGlassBase , global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders.IFolder
	{
			
					/// <summary>
			/// The Title field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: eb3234e7-a11c-4b3a-b6eb-6937993cfa64</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(ISocial_Media_Folder_Constants.Title_FieldName)]
						string Title  { get; set; }
				}

	public static partial class ISocial_Media_Folder_Constants{

			public const string TemplateIdString = "76f0cd1b-032f-4b7d-9ca3-b82fad99f1ff";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Social Media Folder";

					
			public static readonly Guid Title_FieldId = new Guid("eb3234e7-a11c-4b3a-b6eb-6937993cfa64");
			public const string Title_FieldName = "Title";
			
			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Items
{


 	/// <summary>
	/// ISite Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Shared Content/Items/Site</para>	
	/// <para>ID: 78e945be-1f85-4be2-b31e-016f262d28cf</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISite_Constants.TemplateIdString )] //, Cachable = true
	public partial interface ISite : IGlassBase , global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Items.IBase_Content
	{
			
					/// <summary>
			/// The Copyright field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: cc4f54ca-5a98-4e81-97a8-e43e9480df22</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(ISite_Constants.Copyright_FieldName)]
						string Copyright  { get; set; }
					
					/// <summary>
			/// The Default Footer field.
			/// <para></para>
			/// <para>Field Type: Droptree</para>		
			/// <para>Field ID: d43140ac-30fb-481d-ac5a-bae7e9622d12</para>
			/// <para>Custom Data: type=GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders.IFooter_Folder</para>
			/// </summary>
							[SitecoreField(FieldName="Default Footer")]
									GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders.IFooter_Folder Default_Footer  { get; set; }
					
					/// <summary>
			/// The Default Header field.
			/// <para></para>
			/// <para>Field Type: Droptree</para>		
			/// <para>Field ID: 385e8c5a-6e98-4712-a1e8-527f5a19c4be</para>
			/// <para>Custom Data: type=GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders.IHeader_Folder</para>
			/// </summary>
							[SitecoreField(FieldName="Default Header")]
									GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders.IHeader_Folder Default_Header  { get; set; }
					
					/// <summary>
			/// The Logo Link field.
			/// <para></para>
			/// <para>Field Type: General Link</para>		
			/// <para>Field ID: 21adda31-7e4a-4338-a4da-54b6932e6122</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(ISite_Constants.Logo_Link_FieldName)]
						Link Logo_Link  { get; set; }
					
					/// <summary>
			/// The Logo field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: 699897fb-92a4-4b50-bfd3-f859d68247a5</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(ISite_Constants.Logo_FieldName)]
						string Logo  { get; set; }
					
					/// <summary>
			/// The Global Search Box Watermark field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: d4b3b091-7398-4e87-99b5-400b8fec9f5b</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(ISite_Constants.Global_Search_Box_Watermark_FieldName)]
						string Global_Search_Box_Watermark  { get; set; }
					
					/// <summary>
			/// The Global Search Page field.
			/// <para></para>
			/// <para>Field Type: Droptree</para>		
			/// <para>Field ID: 75c1f7fe-1d49-4db1-8250-3202760d353d</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(ISite_Constants.Global_Search_Page_FieldName)]
						Guid Global_Search_Page  { get; set; }
				}

	public static partial class ISite_Constants{

			public const string TemplateIdString = "78e945be-1f85-4be2-b31e-016f262d28cf";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Site";

					
			public static readonly Guid Copyright_FieldId = new Guid("cc4f54ca-5a98-4e81-97a8-e43e9480df22");
			public const string Copyright_FieldName = "Copyright";
			
					
			public static readonly Guid Default_Footer_FieldId = new Guid("d43140ac-30fb-481d-ac5a-bae7e9622d12");
			public const string Default_Footer_FieldName = "Default Footer";
			
					
			public static readonly Guid Default_Header_FieldId = new Guid("385e8c5a-6e98-4712-a1e8-527f5a19c4be");
			public const string Default_Header_FieldName = "Default Header";
			
					
			public static readonly Guid Logo_Link_FieldId = new Guid("21adda31-7e4a-4338-a4da-54b6932e6122");
			public const string Logo_Link_FieldName = "Logo Link";
			
					
			public static readonly Guid Logo_FieldId = new Guid("699897fb-92a4-4b50-bfd3-f859d68247a5");
			public const string Logo_FieldName = "Logo";
			
					
			public static readonly Guid Global_Search_Box_Watermark_FieldId = new Guid("d4b3b091-7398-4e87-99b5-400b8fec9f5b");
			public const string Global_Search_Box_Watermark_FieldName = "Global Search Box Watermark";
			
					
			public static readonly Guid Global_Search_Page_FieldId = new Guid("75c1f7fe-1d49-4db1-8250-3202760d353d");
			public const string Global_Search_Page_FieldName = "Global Search Page";
			
			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Pages
{


 	/// <summary>
	/// IHome_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Pages/Home Page</para>	
	/// <para>ID: 7f2002e5-3a1b-46e0-9e63-5b7aed0e87a6</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHome_Page_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IHome_Page : IGlassBase , global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Pages.IBase_Page
	{
		}

	public static partial class IHome_Page_Constants{

			public const string TemplateIdString = "7f2002e5-3a1b-46e0-9e63-5b7aed0e87a6";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Home Page";

					
			public static readonly Guid Page_Content_FieldId = new Guid("90bf8b70-3ffc-47e4-af83-0068e07acd23");
			public const string Page_Content_FieldName = "Page Content";
			
					
			public static readonly Guid Page_Title_FieldId = new Guid("ab02e860-c889-4490-8a5f-90959a1b4b17");
			public const string Page_Title_FieldName = "Page Title";
			
					
			public static readonly Guid Meta_Description_FieldId = new Guid("3a5ff9d9-7147-4621-9735-865209cb1520");
			public const string Meta_Description_FieldName = "Meta Description";
			
					
			public static readonly Guid Meta_Keywords_FieldId = new Guid("20c67f04-069f-45b2-adc5-065619ba179e");
			public const string Meta_Keywords_FieldName = "Meta Keywords";
			
					
			public static readonly Guid Meta_Title_FieldId = new Guid("8c0b738b-8c1e-494c-92cf-0b9eb3c1d44d");
			public const string Meta_Title_FieldName = "Meta Title";
			
					
			public static readonly Guid Robots_No_Follow_FieldId = new Guid("3f9c8123-0885-420c-8d96-ec0927b354d7");
			public const string Robots_No_Follow_FieldName = "Robots No Follow";
			
					
			public static readonly Guid Robots_No_Index_FieldId = new Guid("312d6ee0-198c-4e8e-999c-ed9eac37de56");
			public const string Robots_No_Index_FieldName = "Robots No Index";
			
					
			public static readonly Guid Breadcrumb_Title_FieldId = new Guid("8c6a214c-e205-4eac-b9fb-a35faee235f2");
			public const string Breadcrumb_Title_FieldName = "Breadcrumb Title";
			
					
			public static readonly Guid Include_In_Secondary_Navigation_FieldId = new Guid("79d5eb3d-e589-4ec9-ad98-c866b738e888");
			public const string Include_In_Secondary_Navigation_FieldName = "Include In Secondary Navigation";
			
					
			public static readonly Guid Include_In_Sitemap_FieldId = new Guid("576a1e27-ebaf-4541-a659-a2f25ff0770d");
			public const string Include_In_Sitemap_FieldName = "Include In Sitemap";
			
					
			public static readonly Guid Closing_Body_Snippets_FieldId = new Guid("6af72353-268b-4ddd-a6a3-2d28dd498fb0");
			public const string Closing_Body_Snippets_FieldName = "Closing Body Snippets";
			
					
			public static readonly Guid Head_Snippets_FieldId = new Guid("9260adc8-6166-45b1-93e2-86e717c9d2f3");
			public const string Head_Snippets_FieldName = "Head Snippets";
			
					
			public static readonly Guid CSS_Files_FieldId = new Guid("f3e7feb1-5190-4beb-8370-e2a7c01e04cc");
			public const string CSS_Files_FieldName = "CSS Files";
			
					
			public static readonly Guid JavaScript_Files_FieldId = new Guid("5be0cd9e-b3f4-428a-a226-fd328f3a346c");
			public const string JavaScript_Files_FieldName = "JavaScript Files";
			
					
			public static readonly Guid Link_Label_FieldId = new Guid("dc54c8dc-08f7-4123-acbf-865a39b90947");
			public const string Link_Label_FieldName = "Link Label";
			
					
			public static readonly Guid Short_Description_FieldId = new Guid("a7b0c508-20f9-4e46-9466-a115ab7af677");
			public const string Short_Description_FieldName = "Short Description";
			
					
			public static readonly Guid Thumbnail_FieldId = new Guid("1d79c2d5-dd2a-4d3f-88a3-a9b3998039f6");
			public const string Thumbnail_FieldName = "Thumbnail";
			
			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Pages.Base_Content
{


 	/// <summary>
	/// IBody_Content Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Pages/Base Content/Body Content</para>	
	/// <para>ID: 8f34d3db-8866-4d19-9e3a-11f73761f0db</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBody_Content_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IBody_Content : IGlassBase 
	{
						/// <summary>
			/// The Page Content field.
			/// <para></para>
			/// <para>Field Type: Rich Text</para>		
			/// <para>Field ID: 90bf8b70-3ffc-47e4-af83-0068e07acd23</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IBody_Content_Constants.Page_Content_FieldName, ReadOnly = true)]
						string Page_Content  { get; set; }

			/// <summary>
			/// The Page Content field in RAW format.
			/// <para></para>
			/// <para>Field Type: Rich Text</para>		
			/// <para>Field ID: 90bf8b70-3ffc-47e4-af83-0068e07acd23</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IBody_Content_Constants.Page_Content_FieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
						string Page_Content_Raw  { get; set; }
		
					
					/// <summary>
			/// The Page Title field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: ab02e860-c889-4490-8a5f-90959a1b4b17</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IBody_Content_Constants.Page_Title_FieldName)]
						string Page_Title  { get; set; }
				}

	public static partial class IBody_Content_Constants{

			public const string TemplateIdString = "8f34d3db-8866-4d19-9e3a-11f73761f0db";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Body Content";

					
			public static readonly Guid Page_Content_FieldId = new Guid("90bf8b70-3ffc-47e4-af83-0068e07acd23");
			public const string Page_Content_FieldName = "Page Content";
			
					
			public static readonly Guid Page_Title_FieldId = new Guid("ab02e860-c889-4490-8a5f-90959a1b4b17");
			public const string Page_Title_FieldName = "Page Title";
			
			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Pages.Base_Content
{


 	/// <summary>
	/// IMedia_Assets Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Pages/Base Content/Media Assets</para>	
	/// <para>ID: 9895cc80-53bf-40a5-9d96-b257dd0b8608</para>	
	/// </summary>
	[SitecoreType(TemplateId=IMedia_Assets_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IMedia_Assets : IGlassBase 
	{
			
					/// <summary>
			/// The CSS Files field.
			/// <para></para>
			/// <para>Field Type: Treelist</para>		
			/// <para>Field ID: f3e7feb1-5190-4beb-8370-e2a7c01e04cc</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IMedia_Assets_Constants.CSS_Files_FieldName)]
						IEnumerable<Guid> CSS_Files  { get; set; }
					
					/// <summary>
			/// The JavaScript Files field.
			/// <para></para>
			/// <para>Field Type: Treelist</para>		
			/// <para>Field ID: 5be0cd9e-b3f4-428a-a226-fd328f3a346c</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IMedia_Assets_Constants.JavaScript_Files_FieldName)]
						IEnumerable<Guid> JavaScript_Files  { get; set; }
				}

	public static partial class IMedia_Assets_Constants{

			public const string TemplateIdString = "9895cc80-53bf-40a5-9d96-b257dd0b8608";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Media Assets";

					
			public static readonly Guid CSS_Files_FieldId = new Guid("f3e7feb1-5190-4beb-8370-e2a7c01e04cc");
			public const string CSS_Files_FieldName = "CSS Files";
			
					
			public static readonly Guid JavaScript_Files_FieldId = new Guid("5be0cd9e-b3f4-428a-a226-fd328f3a346c");
			public const string JavaScript_Files_FieldName = "JavaScript Files";
			
			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders
{


 	/// <summary>
	/// IFooter_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Shared Content/Folders/Footer Folder</para>	
	/// <para>ID: a17b9592-df96-4b50-970c-187b3819b634</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFooter_Folder_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IFooter_Folder : IGlassBase , global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders.IFolder
	{
		}

	public static partial class IFooter_Folder_Constants{

			public const string TemplateIdString = "a17b9592-df96-4b50-970c-187b3819b634";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Footer Folder";

			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Pages.Base_Content
{


 	/// <summary>
	/// ISEO Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Pages/Base Content/SEO</para>	
	/// <para>ID: b0fa7702-10ad-477f-8a76-759c299c9dcf</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISEO_Constants.TemplateIdString )] //, Cachable = true
	public partial interface ISEO : IGlassBase 
	{
			
					/// <summary>
			/// The Meta Description field.
			/// <para></para>
			/// <para>Field Type: Multi-Line Text</para>		
			/// <para>Field ID: 3a5ff9d9-7147-4621-9735-865209cb1520</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(ISEO_Constants.Meta_Description_FieldName)]
						string Meta_Description  { get; set; }
					
					/// <summary>
			/// The Meta Keywords field.
			/// <para></para>
			/// <para>Field Type: Multi-Line Text</para>		
			/// <para>Field ID: 20c67f04-069f-45b2-adc5-065619ba179e</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(ISEO_Constants.Meta_Keywords_FieldName)]
						string Meta_Keywords  { get; set; }
					
					/// <summary>
			/// The Meta Title field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: 8c0b738b-8c1e-494c-92cf-0b9eb3c1d44d</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(ISEO_Constants.Meta_Title_FieldName)]
						string Meta_Title  { get; set; }
					
					/// <summary>
			/// The Robots No Follow field.
			/// <para></para>
			/// <para>Field Type: Checkbox</para>		
			/// <para>Field ID: 3f9c8123-0885-420c-8d96-ec0927b354d7</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(ISEO_Constants.Robots_No_Follow_FieldName)]
						bool Robots_No_Follow  { get; set; }
					
					/// <summary>
			/// The Robots No Index field.
			/// <para></para>
			/// <para>Field Type: Checkbox</para>		
			/// <para>Field ID: 312d6ee0-198c-4e8e-999c-ed9eac37de56</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(ISEO_Constants.Robots_No_Index_FieldName)]
						bool Robots_No_Index  { get; set; }
				}

	public static partial class ISEO_Constants{

			public const string TemplateIdString = "b0fa7702-10ad-477f-8a76-759c299c9dcf";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "SEO";

					
			public static readonly Guid Meta_Description_FieldId = new Guid("3a5ff9d9-7147-4621-9735-865209cb1520");
			public const string Meta_Description_FieldName = "Meta Description";
			
					
			public static readonly Guid Meta_Keywords_FieldId = new Guid("20c67f04-069f-45b2-adc5-065619ba179e");
			public const string Meta_Keywords_FieldName = "Meta Keywords";
			
					
			public static readonly Guid Meta_Title_FieldId = new Guid("8c0b738b-8c1e-494c-92cf-0b9eb3c1d44d");
			public const string Meta_Title_FieldName = "Meta Title";
			
					
			public static readonly Guid Robots_No_Follow_FieldId = new Guid("3f9c8123-0885-420c-8d96-ec0927b354d7");
			public const string Robots_No_Follow_FieldName = "Robots No Follow";
			
					
			public static readonly Guid Robots_No_Index_FieldId = new Guid("312d6ee0-198c-4e8e-999c-ed9eac37de56");
			public const string Robots_No_Index_FieldName = "Robots No Index";
			
			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Items
{


 	/// <summary>
	/// ISocial_Media Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Shared Content/Items/Social Media</para>	
	/// <para>ID: b563e5e4-24d7-4dab-9a25-a3406ca4d82c</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISocial_Media_Constants.TemplateIdString )] //, Cachable = true
	public partial interface ISocial_Media : IGlassBase , global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Items.IBase_Content
	{
			
					/// <summary>
			/// The Icon field.
			/// <para></para>
			/// <para>Field Type: Image</para>		
			/// <para>Field ID: cf9f43b3-8de1-46d2-8b55-55b2aef812a6</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(ISocial_Media_Constants.Icon_FieldName)]
						Image Icon  { get; set; }
					
					/// <summary>
			/// The Link field.
			/// <para></para>
			/// <para>Field Type: General Link</para>		
			/// <para>Field ID: 91e6ecf4-c342-4302-be14-92b6090fcbaf</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(ISocial_Media_Constants.Link_FieldName)]
						Link Link  { get; set; }
				}

	public static partial class ISocial_Media_Constants{

			public const string TemplateIdString = "b563e5e4-24d7-4dab-9a25-a3406ca4d82c";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Social Media";

					
			public static readonly Guid Icon_FieldId = new Guid("cf9f43b3-8de1-46d2-8b55-55b2aef812a6");
			public const string Icon_FieldName = "Icon";
			
					
			public static readonly Guid Link_FieldId = new Guid("91e6ecf4-c342-4302-be14-92b6090fcbaf");
			public const string Link_FieldName = "Link";
			
			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders
{


 	/// <summary>
	/// ITop_Navigation_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Shared Content/Folders/Top Navigation Folder</para>	
	/// <para>ID: b7b35318-f34c-460a-8a63-95f7dda64dde</para>	
	/// </summary>
	[SitecoreType(TemplateId=ITop_Navigation_Folder_Constants.TemplateIdString )] //, Cachable = true
	public partial interface ITop_Navigation_Folder : IGlassBase , global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders.IFolder
	{
		}

	public static partial class ITop_Navigation_Folder_Constants{

			public const string TemplateIdString = "b7b35318-f34c-460a-8a63-95f7dda64dde";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Top Navigation Folder";

			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Pages
{


 	/// <summary>
	/// IBase_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Pages/Base Page</para>	
	/// <para>ID: bc09bd6f-d6c9-4868-84fd-1037fb84017e</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBase_Page_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IBase_Page : IGlassBase , global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Pages.Base_Content.IBody_Content, global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Pages.Base_Content.ISEO, global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Pages.Base_Content.INavigation, global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Pages.Base_Content.IFreeform_Snippets, global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Pages.Base_Content.IMedia_Assets, global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Items.IBase_Content, global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Pages.Base_Content.IList_Item
	{
		}

	public static partial class IBase_Page_Constants{

			public const string TemplateIdString = "bc09bd6f-d6c9-4868-84fd-1037fb84017e";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Base Page";

					
			public static readonly Guid Page_Content_FieldId = new Guid("90bf8b70-3ffc-47e4-af83-0068e07acd23");
			public const string Page_Content_FieldName = "Page Content";
			
					
			public static readonly Guid Page_Title_FieldId = new Guid("ab02e860-c889-4490-8a5f-90959a1b4b17");
			public const string Page_Title_FieldName = "Page Title";
			
					
			public static readonly Guid Meta_Description_FieldId = new Guid("3a5ff9d9-7147-4621-9735-865209cb1520");
			public const string Meta_Description_FieldName = "Meta Description";
			
					
			public static readonly Guid Meta_Keywords_FieldId = new Guid("20c67f04-069f-45b2-adc5-065619ba179e");
			public const string Meta_Keywords_FieldName = "Meta Keywords";
			
					
			public static readonly Guid Meta_Title_FieldId = new Guid("8c0b738b-8c1e-494c-92cf-0b9eb3c1d44d");
			public const string Meta_Title_FieldName = "Meta Title";
			
					
			public static readonly Guid Robots_No_Follow_FieldId = new Guid("3f9c8123-0885-420c-8d96-ec0927b354d7");
			public const string Robots_No_Follow_FieldName = "Robots No Follow";
			
					
			public static readonly Guid Robots_No_Index_FieldId = new Guid("312d6ee0-198c-4e8e-999c-ed9eac37de56");
			public const string Robots_No_Index_FieldName = "Robots No Index";
			
					
			public static readonly Guid Breadcrumb_Title_FieldId = new Guid("8c6a214c-e205-4eac-b9fb-a35faee235f2");
			public const string Breadcrumb_Title_FieldName = "Breadcrumb Title";
			
					
			public static readonly Guid Include_In_Secondary_Navigation_FieldId = new Guid("79d5eb3d-e589-4ec9-ad98-c866b738e888");
			public const string Include_In_Secondary_Navigation_FieldName = "Include In Secondary Navigation";
			
					
			public static readonly Guid Include_In_Sitemap_FieldId = new Guid("576a1e27-ebaf-4541-a659-a2f25ff0770d");
			public const string Include_In_Sitemap_FieldName = "Include In Sitemap";
			
					
			public static readonly Guid Closing_Body_Snippets_FieldId = new Guid("6af72353-268b-4ddd-a6a3-2d28dd498fb0");
			public const string Closing_Body_Snippets_FieldName = "Closing Body Snippets";
			
					
			public static readonly Guid Head_Snippets_FieldId = new Guid("9260adc8-6166-45b1-93e2-86e717c9d2f3");
			public const string Head_Snippets_FieldName = "Head Snippets";
			
					
			public static readonly Guid CSS_Files_FieldId = new Guid("f3e7feb1-5190-4beb-8370-e2a7c01e04cc");
			public const string CSS_Files_FieldName = "CSS Files";
			
					
			public static readonly Guid JavaScript_Files_FieldId = new Guid("5be0cd9e-b3f4-428a-a226-fd328f3a346c");
			public const string JavaScript_Files_FieldName = "JavaScript Files";
			
					
			public static readonly Guid Link_Label_FieldId = new Guid("dc54c8dc-08f7-4123-acbf-865a39b90947");
			public const string Link_Label_FieldName = "Link Label";
			
					
			public static readonly Guid Short_Description_FieldId = new Guid("a7b0c508-20f9-4e46-9466-a115ab7af677");
			public const string Short_Description_FieldName = "Short Description";
			
					
			public static readonly Guid Thumbnail_FieldId = new Guid("1d79c2d5-dd2a-4d3f-88a3-a9b3998039f6");
			public const string Thumbnail_FieldName = "Thumbnail";
			
			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders
{


 	/// <summary>
	/// ICarousel_Slides_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Shared Content/Folders/Carousel Slides Folder</para>	
	/// <para>ID: bd32ab5a-7dbc-4351-ad50-e14554073b05</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICarousel_Slides_Folder_Constants.TemplateIdString )] //, Cachable = true
	public partial interface ICarousel_Slides_Folder : IGlassBase , global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders.IFolder
	{
		}

	public static partial class ICarousel_Slides_Folder_Constants{

			public const string TemplateIdString = "bd32ab5a-7dbc-4351-ad50-e14554073b05";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Carousel Slides Folder";

			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders
{


 	/// <summary>
	/// ICarousels_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Shared Content/Folders/Carousels Folder</para>	
	/// <para>ID: c780df01-5072-4e75-9350-0f65e29c8104</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICarousels_Folder_Constants.TemplateIdString )] //, Cachable = true
	public partial interface ICarousels_Folder : IGlassBase , global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders.IFolder
	{
		}

	public static partial class ICarousels_Folder_Constants{

			public const string TemplateIdString = "c780df01-5072-4e75-9350-0f65e29c8104";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Carousels Folder";

			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Items
{


 	/// <summary>
	/// IFooter_Link_Category Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Shared Content/Items/Footer Link Category</para>	
	/// <para>ID: d40c4e94-4d81-4381-a112-c866af4e9670</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFooter_Link_Category_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IFooter_Link_Category : IGlassBase , global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Items.IText_Link
	{
		}

	public static partial class IFooter_Link_Category_Constants{

			public const string TemplateIdString = "d40c4e94-4d81-4381-a112-c866af4e9670";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Footer Link Category";

					
			public static readonly Guid Link_FieldId = new Guid("66b7bea7-b2dc-446e-9878-003799eb99fc");
			public const string Link_FieldName = "Link";
			
					
			public static readonly Guid Title_FieldId = new Guid("18489f03-048b-4b95-831b-7ae01bb7ced2");
			public const string Title_FieldName = "Title";
			
			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders
{


 	/// <summary>
	/// IFooter_Link_Categories_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Shared Content/Folders/Footer Link Categories Folder</para>	
	/// <para>ID: ea11c036-9961-459a-acaf-b8acf8971c28</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFooter_Link_Categories_Folder_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IFooter_Link_Categories_Folder : IGlassBase , global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Folders.IFolder
	{
		}

	public static partial class IFooter_Link_Categories_Folder_Constants{

			public const string TemplateIdString = "ea11c036-9961-459a-acaf-b8acf8971c28";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Footer Link Categories Folder";

			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Items
{


 	/// <summary>
	/// ICarousel Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Shared Content/Items/Carousel</para>	
	/// <para>ID: eb19541a-c21b-46ba-8ba2-6a4626d748b3</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICarousel_Constants.TemplateIdString )] //, Cachable = true
	public partial interface ICarousel : IGlassBase , global::GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Shared_Content.Items.IBase_Content
	{
			
					/// <summary>
			/// The Slides field.
			/// <para></para>
			/// <para>Field Type: Treelist</para>		
			/// <para>Field ID: 20b05d58-db54-4f57-a82c-838f7a2db739</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(ICarousel_Constants.Slides_FieldName)]
						IEnumerable<Guid> Slides  { get; set; }
				}

	public static partial class ICarousel_Constants{

			public const string TemplateIdString = "eb19541a-c21b-46ba-8ba2-6a4626d748b3";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Carousel";

					
			public static readonly Guid Slides_FieldId = new Guid("20b05d58-db54-4f57-a82c-838f7a2db739");
			public const string Slides_FieldName = "Slides";
			
			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Pages.Base_Content
{


 	/// <summary>
	/// IFreeform_Snippets Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Pages/Base Content/Freeform Snippets</para>	
	/// <para>ID: efb4c9e2-1f38-4e6b-9846-a099feaf354c</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFreeform_Snippets_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IFreeform_Snippets : IGlassBase 
	{
			
					/// <summary>
			/// The Closing Body Snippets field.
			/// <para></para>
			/// <para>Field Type: Multi-Line Text</para>		
			/// <para>Field ID: 6af72353-268b-4ddd-a6a3-2d28dd498fb0</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IFreeform_Snippets_Constants.Closing_Body_Snippets_FieldName)]
						string Closing_Body_Snippets  { get; set; }
					
					/// <summary>
			/// The Head Snippets field.
			/// <para></para>
			/// <para>Field Type: Multi-Line Text</para>		
			/// <para>Field ID: 9260adc8-6166-45b1-93e2-86e717c9d2f3</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IFreeform_Snippets_Constants.Head_Snippets_FieldName)]
						string Head_Snippets  { get; set; }
				}

	public static partial class IFreeform_Snippets_Constants{

			public const string TemplateIdString = "efb4c9e2-1f38-4e6b-9846-a099feaf354c";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Freeform Snippets";

					
			public static readonly Guid Closing_Body_Snippets_FieldId = new Guid("6af72353-268b-4ddd-a6a3-2d28dd498fb0");
			public const string Closing_Body_Snippets_FieldName = "Closing Body Snippets";
			
					
			public static readonly Guid Head_Snippets_FieldId = new Guid("9260adc8-6166-45b1-93e2-86e717c9d2f3");
			public const string Head_Snippets_FieldName = "Head Snippets";
			
			

	}


}
namespace GlassMapperWalkthrough.Domain.Models.Sitecore_Templates.Glass_Mapper_Walkthrough.Pages.Base_Content
{


 	/// <summary>
	/// INavigation Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Glass Mapper Walkthrough/Pages/Base Content/Navigation</para>	
	/// <para>ID: fbc1c286-8a4a-4634-baf9-d4e9d583e7b0</para>	
	/// </summary>
	[SitecoreType(TemplateId=INavigation_Constants.TemplateIdString )] //, Cachable = true
	public partial interface INavigation : IGlassBase 
	{
			
					/// <summary>
			/// The Breadcrumb Title field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: 8c6a214c-e205-4eac-b9fb-a35faee235f2</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(INavigation_Constants.Breadcrumb_Title_FieldName)]
						string Breadcrumb_Title  { get; set; }
					
					/// <summary>
			/// The Include In Secondary Navigation field.
			/// <para></para>
			/// <para>Field Type: Checkbox</para>		
			/// <para>Field ID: 79d5eb3d-e589-4ec9-ad98-c866b738e888</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(INavigation_Constants.Include_In_Secondary_Navigation_FieldName)]
						bool Include_In_Secondary_Navigation  { get; set; }
					
					/// <summary>
			/// The Include In Sitemap field.
			/// <para></para>
			/// <para>Field Type: Checkbox</para>		
			/// <para>Field ID: 576a1e27-ebaf-4541-a659-a2f25ff0770d</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(INavigation_Constants.Include_In_Sitemap_FieldName)]
						bool Include_In_Sitemap  { get; set; }
				}

	public static partial class INavigation_Constants{

			public const string TemplateIdString = "fbc1c286-8a4a-4634-baf9-d4e9d583e7b0";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Navigation";

					
			public static readonly Guid Breadcrumb_Title_FieldId = new Guid("8c6a214c-e205-4eac-b9fb-a35faee235f2");
			public const string Breadcrumb_Title_FieldName = "Breadcrumb Title";
			
					
			public static readonly Guid Include_In_Secondary_Navigation_FieldId = new Guid("79d5eb3d-e589-4ec9-ad98-c866b738e888");
			public const string Include_In_Secondary_Navigation_FieldName = "Include In Secondary Navigation";
			
					
			public static readonly Guid Include_In_Sitemap_FieldId = new Guid("576a1e27-ebaf-4541-a659-a2f25ff0770d");
			public const string Include_In_Sitemap_FieldName = "Include In Sitemap";
			
			

	}


}
